// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	contextx "github.com/blackhorseya/lobster/internal/pkg/contextx"
	mock "github.com/stretchr/testify/mock"

	okr "github.com/blackhorseya/lobster/internal/pkg/entities/biz/okr"
)

// IBiz is an autogenerated mock type for the IBiz type
type IBiz struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx
func (_m *IBiz) Count(ctx contextx.Contextx) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(contextx.Contextx) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, obj
func (_m *IBiz) Create(ctx contextx.Contextx, obj *okr.Objective) (*okr.Objective, error) {
	ret := _m.Called(ctx, obj)

	var r0 *okr.Objective
	if rf, ok := ret.Get(0).(func(contextx.Contextx, *okr.Objective) *okr.Objective); ok {
		r0 = rf(ctx, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*okr.Objective)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, *okr.Objective) error); ok {
		r1 = rf(ctx, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *IBiz) Delete(ctx contextx.Contextx, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, page, size
func (_m *IBiz) List(ctx contextx.Contextx, page int, size int) ([]*okr.Objective, error) {
	ret := _m.Called(ctx, page, size)

	var r0 []*okr.Objective
	if rf, ok := ret.Get(0).(func(contextx.Contextx, int, int) []*okr.Objective); ok {
		r0 = rf(ctx, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*okr.Objective)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, int, int) error); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, updated
func (_m *IBiz) Update(ctx contextx.Contextx, updated *okr.Objective) (*okr.Objective, error) {
	ret := _m.Called(ctx, updated)

	var r0 *okr.Objective
	if rf, ok := ret.Get(0).(func(contextx.Contextx, *okr.Objective) *okr.Objective); ok {
		r0 = rf(ctx, updated)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*okr.Objective)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, *okr.Objective) error); ok {
		r1 = rf(ctx, updated)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
