// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	contextx "github.com/blackhorseya/lobster/internal/pkg/base/contextx"
	entitytask "github.com/blackhorseya/lobster/internal/pkg/entity/todo"

	mock "github.com/stretchr/testify/mock"
)

// IBiz is an autogenerated mock type for the IBiz type
type IBiz struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx
func (_m *IBiz) Count(ctx contextx.Contextx) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(contextx.Contextx) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, title
func (_m *IBiz) Create(ctx contextx.Contextx, title string) (*entitytask.Task, error) {
	ret := _m.Called(ctx, title)

	var r0 *entitytask.Task
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string) *entitytask.Task); ok {
		r0 = rf(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entitytask.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *IBiz) Delete(ctx contextx.Contextx, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(contextx.Contextx, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *IBiz) GetByID(ctx contextx.Contextx, id int64) (*entitytask.Task, error) {
	ret := _m.Called(ctx, id)

	var r0 *entitytask.Task
	if rf, ok := ret.Get(0).(func(contextx.Contextx, int64) *entitytask.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entitytask.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, page, size
func (_m *IBiz) List(ctx contextx.Contextx, page int, size int) ([]*entitytask.Task, error) {
	ret := _m.Called(ctx, page, size)

	var r0 []*entitytask.Task
	if rf, ok := ret.Get(0).(func(contextx.Contextx, int, int) []*entitytask.Task); ok {
		r0 = rf(ctx, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entitytask.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, int, int) error); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ModifyTitle provides a mock function with given fields: ctx, id, title
func (_m *IBiz) ModifyTitle(ctx contextx.Contextx, id int64, title string) (*entitytask.Task, error) {
	ret := _m.Called(ctx, id, title)

	var r0 *entitytask.Task
	if rf, ok := ret.Get(0).(func(contextx.Contextx, int64, string) *entitytask.Task); ok {
		r0 = rf(ctx, id, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entitytask.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, int64, string) error); ok {
		r1 = rf(ctx, id, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *IBiz) UpdateStatus(ctx contextx.Contextx, id int64, status entitytask.Status) (*entitytask.Task, error) {
	ret := _m.Called(ctx, id, status)

	var r0 *entitytask.Task
	if rf, ok := ret.Get(0).(func(contextx.Contextx, int64, entitytask.Status) *entitytask.Task); ok {
		r0 = rf(ctx, id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entitytask.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, int64, entitytask.Status) error); ok {
		r1 = rf(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
