// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package repo

import (
	"github.com/blackhorseya/lobster/internal/pkg/entity/config"
	"github.com/blackhorseya/lobster/internal/pkg/infra/databases"
	"github.com/blackhorseya/lobster/internal/pkg/infra/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateRepo serve caller to create an IRepo
func CreateRepo(path string) (IRepo, error) {
	viper, err := config.New(path)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	databasesOptions, err := databases.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	db, err := databases.NewMariaDB(databasesOptions)
	if err != nil {
		return nil, err
	}
	iRepo := NewImpl(db)
	return iRepo, nil
}

// wire.go:

var testProviderSet = wire.NewSet(log.ProviderSet, config.ProviderSet, databases.ProviderSet, NewImpl)
