// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package goal

import (
	"github.com/blackhorseya/lobster/internal/app/lobster/biz/goal/repo"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// CreateIBiz serve caller to create an IBiz
func CreateIBiz(logger *zap.Logger, repo2 repo.IRepo) (IBiz, error) {
	iBiz := NewImpl(logger, repo2)
	return iBiz, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
