// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/blackhorseya/lobster/internal/app"
	"github.com/blackhorseya/lobster/internal/app/apis"
	"github.com/blackhorseya/lobster/internal/app/apis/health"
	todo2 "github.com/blackhorseya/lobster/internal/app/apis/todo"
	"github.com/blackhorseya/lobster/internal/app/biz"
	"github.com/blackhorseya/lobster/internal/app/biz/todo"
	"github.com/blackhorseya/lobster/internal/app/biz/todo/repo"
	"github.com/blackhorseya/lobster/internal/pkg/config"
	"github.com/blackhorseya/lobster/internal/pkg/databases"
	"github.com/blackhorseya/lobster/internal/pkg/transports/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateInjector(path2 string) (*app.Injector, error) {
	configConfig, err := config.NewConfig(path2)
	if err != nil {
		return nil, err
	}
	iHandler := health.NewImpl()
	client, err := databases.NewMongoDB(configConfig)
	if err != nil {
		return nil, err
	}
	iRepo := repo.NewImpl(client)
	iBiz := todo.NewImpl(iRepo)
	todoIHandler := todo2.NewImpl(iBiz)
	initHandlers := apis.CreateInitHandlerFn(iHandler, todoIHandler)
	engine := http.NewGinEngine(configConfig, initHandlers)
	injector := app.NewInjector(engine, configConfig)
	return injector, nil
}

// wire.go:

var providerSet = wire.NewSet(app.ProviderSet, config.ProviderSet, http.ProviderSet, databases.ProviderSet, apis.ProviderSet, biz.ProviderSet)
