// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/blackhorseya/lobster/internal/cmd"
	"github.com/blackhorseya/lobster/internal/pkg/config"
	"github.com/google/wire"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func CreateCommand() (*cobra.Command, error) {
	command := cmd.NewCommand()
	return command, nil
}

// wire.go:

var providerSet = wire.NewSet(cmd.ProviderSet, config.ProviderSet)
