// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/blackhorseya/lobster/internal/app/lobster"
	"github.com/blackhorseya/lobster/internal/app/lobster/apis"
	goal2 "github.com/blackhorseya/lobster/internal/app/lobster/apis/goal"
	health2 "github.com/blackhorseya/lobster/internal/app/lobster/apis/health"
	result2 "github.com/blackhorseya/lobster/internal/app/lobster/apis/result"
	task2 "github.com/blackhorseya/lobster/internal/app/lobster/apis/task"
	user2 "github.com/blackhorseya/lobster/internal/app/lobster/apis/user"
	"github.com/blackhorseya/lobster/internal/app/lobster/biz"
	"github.com/blackhorseya/lobster/internal/app/lobster/biz/goal"
	repo3 "github.com/blackhorseya/lobster/internal/app/lobster/biz/goal/repo"
	"github.com/blackhorseya/lobster/internal/app/lobster/biz/health"
	"github.com/blackhorseya/lobster/internal/app/lobster/biz/health/repo"
	"github.com/blackhorseya/lobster/internal/app/lobster/biz/result"
	repo4 "github.com/blackhorseya/lobster/internal/app/lobster/biz/result/repo"
	"github.com/blackhorseya/lobster/internal/app/lobster/biz/task"
	repo2 "github.com/blackhorseya/lobster/internal/app/lobster/biz/task/repo"
	"github.com/blackhorseya/lobster/internal/app/lobster/biz/user"
	repo5 "github.com/blackhorseya/lobster/internal/app/lobster/biz/user/repo"
	"github.com/blackhorseya/lobster/internal/pkg/app"
	"github.com/blackhorseya/lobster/internal/pkg/entity/config"
	"github.com/blackhorseya/lobster/internal/pkg/infra/databases"
	"github.com/blackhorseya/lobster/internal/pkg/infra/log"
	"github.com/blackhorseya/lobster/internal/pkg/infra/token"
	"github.com/blackhorseya/lobster/internal/pkg/infra/transports/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateApp(path2 string) (*app.Application, error) {
	viper, err := config.New(path2)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	lobsterOptions, err := lobster.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	httpOptions, err := http.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	databasesOptions, err := databases.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	db, err := databases.NewMariaDB(databasesOptions)
	if err != nil {
		return nil, err
	}
	iRepo := repo.NewImpl(db)
	iBiz := health.NewImpl(logger, iRepo)
	iHandler := health2.NewImpl(logger, iBiz)
	repoIRepo := repo2.NewImpl(db)
	taskIBiz := task.NewImpl(logger, repoIRepo)
	taskIHandler := task2.NewImpl(logger, taskIBiz)
	iRepo2 := repo3.NewImpl(db)
	goalIBiz := goal.NewImpl(logger, iRepo2)
	goalIHandler := goal2.NewImpl(logger, goalIBiz)
	iRepo3 := repo4.NewImpl(db)
	resultIBiz := result.NewImpl(logger, iRepo3)
	resultIHandler := result2.NewImpl(logger, resultIBiz)
	iRepo4 := repo5.NewImpl(logger, db)
	tokenOptions, err := token.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	factory, err := token.New(tokenOptions, logger)
	if err != nil {
		return nil, err
	}
	userIBiz := user.NewImpl(logger, iRepo4, factory)
	userIHandler := user2.NewImpl(logger, userIBiz)
	initHandlers := apis.CreateInitHandlerFn(iHandler, taskIHandler, goalIHandler, resultIHandler, userIHandler)
	engine := http.NewRouter(httpOptions, logger, initHandlers)
	server, err := http.New(httpOptions, logger, engine)
	if err != nil {
		return nil, err
	}
	application, err := lobster.New(lobsterOptions, logger, server)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

var providerSet = wire.NewSet(lobster.ProviderSet, log.ProviderSet, config.ProviderSet, http.ProviderSet, databases.ProviderSet, token.ProviderSet, apis.ProviderSet, biz.ProviderSet)
