// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package goal

import (
	"github.com/blackhorseya/lobster/internal/app/lobster/biz/goal"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func CreateIHandler(logger *zap.Logger, biz goal.IBiz) (IHandler, error) {
	iHandler := NewImpl(logger, biz)
	return iHandler, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
