app:
  name: "lobster"

http:
  port: 8080
  mode: "debug"

db:
  debug: true
  mariadb: "lobster:changeme@tcp(localhost:3306)/lobster?charset=utf8"
  url: "mongodb://lobster-app:changeme@localhost:27019/lobster-db/?connect=direct&authSource=lobster-db"

log:
  format: text
  level: debug