app:
  name: "lobster"

http:
  port: 8080
  mode: "debug"

db:
  debug: true
  url: "mongodb://lobster-app:changeme@localhost:27019/lobster-db/?connect=direct&authSource=lobster-db"

log:
  format: text
  level: debug