// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	contextx "github.com/blackhorseya/lobster/internal/pkg/contextx"
	mock "github.com/stretchr/testify/mock"

	pb "github.com/blackhorseya/lobster/internal/pkg/pb"
)

// IRepo is an autogenerated mock type for the IRepo type
type IRepo struct {
	mock.Mock
}

// QueryInfoByEmail provides a mock function with given fields: ctx, email
func (_m *IRepo) QueryInfoByEmail(ctx contextx.Contextx, email string) (*pb.Profile, error) {
	ret := _m.Called(ctx, email)

	var r0 *pb.Profile
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string) *pb.Profile); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Profile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRegister provides a mock function with given fields: ctx, newUser
func (_m *IRepo) UserRegister(ctx contextx.Contextx, newUser pb.Profile) (*pb.Profile, error) {
	ret := _m.Called(ctx, newUser)

	var r0 *pb.Profile
	if rf, ok := ret.Get(0).(func(contextx.Contextx, pb.Profile) *pb.Profile); ok {
		r0 = rf(ctx, newUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Profile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, pb.Profile) error); ok {
		r1 = rf(ctx, newUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
