// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	contextx "github.com/blackhorseya/lobster/internal/pkg/contextx"

	mock "github.com/stretchr/testify/mock"

	okr "github.com/blackhorseya/lobster/internal/pkg/entities/biz/okr"
)

// IBiz is an autogenerated mock type for the IBiz type
type IBiz struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *IBiz) Delete(ctx contextx.Contextx, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *IBiz) GetByID(ctx contextx.Contextx, id string) (*okr.KeyResult, error) {
	ret := _m.Called(ctx, id)

	var r0 *okr.KeyResult
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string) *okr.KeyResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*okr.KeyResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkToGoal provides a mock function with given fields: ctx, created
func (_m *IBiz) LinkToGoal(ctx contextx.Contextx, created *okr.KeyResult) (*okr.KeyResult, error) {
	ret := _m.Called(ctx, created)

	var r0 *okr.KeyResult
	if rf, ok := ret.Get(0).(func(contextx.Contextx, *okr.KeyResult) *okr.KeyResult); ok {
		r0 = rf(ctx, created)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*okr.KeyResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, *okr.KeyResult) error); ok {
		r1 = rf(ctx, created)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, page, size
func (_m *IBiz) List(ctx contextx.Contextx, page int, size int) ([]*okr.KeyResult, error) {
	ret := _m.Called(ctx, page, size)

	var r0 []*okr.KeyResult
	if rf, ok := ret.Get(0).(func(contextx.Contextx, int, int) []*okr.KeyResult); ok {
		r0 = rf(ctx, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*okr.KeyResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, int, int) error); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, updated
func (_m *IBiz) Update(ctx contextx.Contextx, updated *okr.KeyResult) (*okr.KeyResult, error) {
	ret := _m.Called(ctx, updated)

	var r0 *okr.KeyResult
	if rf, ok := ret.Get(0).(func(contextx.Contextx, *okr.KeyResult) *okr.KeyResult); ok {
		r0 = rf(ctx, updated)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*okr.KeyResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, *okr.KeyResult) error); ok {
		r1 = rf(ctx, updated)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
